language: python
sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=ocadotechnology
    # REGISTRY_PASS=...
    - secret: "<something long>"

before_script:
  - docker pull "$TRAVIS_REPO_SLUG" || true
script:
  - docker build --pull --cache-from "$TRAVIS_REPO_SLUG" --tag "$TRAVIS_REPO_SLUG" .
  - python setup.py test

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "${$TRAVIS_REPO_SLUG}" "${TRAVIS_REPO_SLUG}:latest"
  - docker tag "${$TRAVIS_REPO_SLUG}" "${$TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}"
deploy:
  provider: script
  script: docker push "${$TRAVIS_REPO_SLUG}:latest" && docker push "${$TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}"
  on:
    branch: master
