language: python
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=
    - REGISTRY_USER=ocadotechnology
    # REGISTRY_PASS=...
    - secret: "<something long>"

before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$TRAVIS_REPO_SLUG" --tag "$TRAVIS_REPO_SLUG" .
  - python setup.py test

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_COMMIT}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_COMMIT}"
  on:
    branch: master
